name: publish

on: push

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://registry.npmjs.org/
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: res
          path: res
      - run: npm i
      - run: mkdir -p res
      - run: echo npm test > res/test.log
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}